### PR TITLE
Type stable unscented transform

### PR DESCRIPTION
**Pull request by johannes-fischer**
This replaces some type instable operations with type stable operations in unscented transform.

### CODE REVIEW

**Review by lassepe — APPROVED** [review]
LGTM

**Review by lassepe — APPROVED** [review]

**Comment by zsunberg** [comment]
Nice, @johannes-fischer I see you have learned some good tricks! Thank you!

**Comment by zsunberg** [comment]
I will give @jamgochiana a chance to comment before merging.

**Comment by johannes-fischer** [comment]
> Nice, @johannes-fischer I see you have learned some good tricks! Thank you!

Yeah, I just realized that my MR in ParticleFilters.jl does the same computations as the unscented transform and did a cross check out of curiosity to see how it's realized here.

**Pull request merged**
